# Generated by Django 4.2.4 on 2023-08-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-is_superstar', '-is_active'), 'verbose_name': 'Usuario'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_distro',
            new_name='is_superstar',
        ),
    ]
