# Generated by Django 4.2.4 on 2023-09-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Superintendente'), ('2', 'Presbítero')], max_length=2, null=True, verbose_name='Rol'),
        ),
    ]
