# Generated by Django 4.2.4 on 2023-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('1', 'Jefe de Distrito'), ('2', 'Jefe de Presbiterio')], default='2', max_length=2, verbose_name='Rol'),
        ),
    ]
