# Generated by Django 4.2.4 on 2023-08-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presbiterio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='bautizados_espiritu',
            field=models.FloatField(verbose_name='Bautizados Espíritu'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='ninnos',
            field=models.PositiveIntegerField(verbose_name='Niños'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='total_afiliacion_oficial',
            field=models.PositiveIntegerField(verbose_name='Total afiliación oficial'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='bautizados_espiritu',
            field=models.FloatField(verbose_name='Bautizados Espíritu'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='ninnos',
            field=models.PositiveIntegerField(verbose_name='Niños'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='total_afiliacion_oficial',
            field=models.PositiveIntegerField(verbose_name='Total afiliación oficial'),
        ),
    ]
