# Generated by Django 4.2.4 on 2023-09-06 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='bautizados_espiritu',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor o igual a cero')], verbose_name='Bautizados Espíritu'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='caballeros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='casa_templo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='casas_cultos',
            field=models.PositiveIntegerField(default=0, verbose_name='Casas Cultos/Células'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='casas_pastorales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='damas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='estudiantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='iglesias',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='jovenes',
            field=models.PositiveIntegerField(default=0, verbose_name='Jóvenes'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='licenciados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='lideres_locales',
            field=models.PositiveIntegerField(default=0, verbose_name='Líderes locales'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='miembros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='ministros',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='misiones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nacionales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='ninnos',
            field=models.PositiveIntegerField(default=0, verbose_name='Niños'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='obreros_tiempo_completo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='ordenados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='presbiteriales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='promedio_asistencia',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Debe ser mayor o igual a cero')]),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='tabernaculos',
            field=models.PositiveIntegerField(default=0, verbose_name='Tabernáculos/Naves'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='templos_no_oficiales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='templos_oficiales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='total_afiliacion_oficial',
            field=models.PositiveIntegerField(default=0, verbose_name='Total afiliación oficial'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='visitantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
