# Generated by Django 4.2.4 on 2023-08-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_presbiterio_user_alter_distrito_bautizados_espiritu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='total_departamento',
            field=models.PositiveIntegerField(default=0, help_text='Incluye niños', verbose_name='Total Departamento / Ministerios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presbiterio',
            name='total_departamento',
            field=models.PositiveIntegerField(default=0, help_text='Incluye niños', verbose_name='Total Departamento / Ministerios'),
            preserve_default=False,
        ),
    ]
