# Generated by Django 4.2.4 on 2023-09-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_distrito_bautizados_espiritu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='total_departamento',
            field=models.PositiveIntegerField(default=0, help_text='Incluye niños', verbose_name='Total Departamento / Ministerios'),
        ),
    ]
