# Generated by Django 4.2.4 on 2023-08-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_distrito_total_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='cant_presbiterios',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de presbiterios'),
        ),
    ]
