# Generated by Django 4.2.4 on 2023-09-18 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0005_resumendistrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendistrito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resumendistrito',
            name='fecha',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
