# Generated by Django 4.2.4 on 2023-08-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_alter_distrito_bautizados_espiritu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='cant_presbiterios',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de presbiterios'),
        ),
    ]
