# Generated by Django 4.2.4 on 2023-09-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_resumendistrito_user_alter_resumendistrito_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumendistrito',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del Distrito'),
        ),
    ]
