# Generated by Django 4.2.4 on 2023-08-16 10:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0006_alter_distrito_cant_presbiterios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ('distrito',)},
        ),
        migrations.AlterModelOptions(
            name='presbiterio',
            options={'ordering': ('distrito', 'user')},
        ),
        migrations.AddField(
            model_name='distrito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
