# Generated by Django 4.2.4 on 2023-09-18 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_resumendistrito_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumendistrito',
            name='fecha_resumen',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha del Resumen'),
            preserve_default=False,
        ),
    ]
