# Generated by Django 4.2.4 on 2023-08-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_alter_distrito_options_alter_presbiterio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Se autosignará la fecha cuando sea creado', verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='presbiterio',
            name='fecha',
            field=models.DateField(auto_now_add=True, help_text='Se autosignará la fecha cuando sea creado', verbose_name='Fecha de creación'),
        ),
    ]
