# Generated by Django 4.2.4 on 2023-09-18 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_main', '0008_resumendistrito_fecha_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumendistrito',
            name='cantidad_meses',
            field=models.PositiveSmallIntegerField(verbose_name='Meses del corte'),
        ),
        migrations.AlterField(
            model_name='resumendistrito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Superintendente'),
        ),
    ]
